//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 10:51:58 AM IST 
//


package edu.yaksha.examapp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roll" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eng" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="math" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="science" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="social-science" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roll",
    "eng",
    "lang",
    "math",
    "science",
    "socialScience"
})
@XmlRootElement(name = "ShowResultRequest")
public class ShowResultRequest {

    protected int roll;
    protected int eng;
    protected int lang;
    protected int math;
    protected int science;
    @XmlElement(name = "social-science")
    protected int socialScience;

    /**
     * Gets the value of the roll property.
     * 
     */
    public int getRoll() {
        return roll;
    }

    /**
     * Sets the value of the roll property.
     * 
     */
    public void setRoll(int value) {
        this.roll = value;
    }

    /**
     * Gets the value of the eng property.
     * 
     */
    public int getEng() {
        return eng;
    }

    /**
     * Sets the value of the eng property.
     * 
     */
    public void setEng(int value) {
        this.eng = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     */
    public int getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     */
    public void setLang(int value) {
        this.lang = value;
    }

    /**
     * Gets the value of the math property.
     * 
     */
    public int getMath() {
        return math;
    }

    /**
     * Sets the value of the math property.
     * 
     */
    public void setMath(int value) {
        this.math = value;
    }

    /**
     * Gets the value of the science property.
     * 
     */
    public int getScience() {
        return science;
    }

    /**
     * Sets the value of the science property.
     * 
     */
    public void setScience(int value) {
        this.science = value;
    }

    /**
     * Gets the value of the socialScience property.
     * 
     */
    public int getSocialScience() {
        return socialScience;
    }

    /**
     * Sets the value of the socialScience property.
     * 
     */
    public void setSocialScience(int value) {
        this.socialScience = value;
    }

}
